version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: java-spting-api
    build: ./
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/test_database
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_database